id: P587A2A9B
initial_creation_type: input
source_metadata:
  title: Bhikṣuṇī Lakṣmī
  language: en
  description: 'Texts by and about the Kashmiri nun Bhikṣuṇī Lakṣmī/Lakṣmīṅkarā, known
    to Tibetans as Gelongma Palmo (dge slong ma dpal mo):'
  volume:
    ed4cbceb9d8d4817a45aa340ce1ce4a2:
      title: Praise of Noble Avalokiteśvara
      parent: Praise
    6eaaf9f2376b4801876d83aefc243755:
      title: Praise of Noble Avalokiteśvara (Tengyur version)
      parent: Praise
    19953494105a439eb08dfce0f1f0311f:
      title: Seven-Branch Offering to Tārā
      parent: Seven-Branch Offering
created_at: '2022-03-01T02:16:24.636292'
last_modified_at: '2022-03-01T02:16:24.636297'
